---
# A UI-based rules plugin for Nukkit
# Copyright (C) 2020 KygekTeam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

name: KygekRulesUI
main: org.kygekteam.kygekrulesui.Main
api: "1.0.0"
version: "1.2.0"
author: KygekTeam
website: "https://github.com/KygekTeam/KygekRulesUI-Nukkit"

permissions:
  kygekrulesui.rules:
    description: Permission to use KygekRulesUI
    default: true
...
